name: Playwright Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать проект
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Установить зависимости
        run: |
          pip install -r requirements.txt

      - name: Установить браузеры Playwright
        run: |
          playwright install --with-deps chromium

      - name: Проверить Playwright
        run: |
          python -c "
      from playwright.sync_api import sync_playwright
      with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto('https://moskva.beeline.ru/spam-feedback/', timeout=30000)
        print(page.title())
        browser.close()
      "

      - name: Запустить тесты
        run: |
          pytest